name: Build Pipeline
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  application:
    runs-on: ubuntu-latest
    name: 
    steps:
      - name: pull repository
        uses: actions/checkout@v4
      - name: setup program language libraries -  python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install dependencies  - python
        run: |
          python -m pip install --upgrade pip         
      - name: setup program language libraries -  java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: install dependencies - java
        run: |
          sudo apt-get install maven -y
      - name: build and test application - python
        run: |
          cd python
          pip install -r requirements.txt
          coverage run -m unittest discover
          coverage report -m
          coverage xml
      - name: build and test application - java
        run: |
          cd java
          mvn clean test
          mvn jacoco:report